### PR TITLE
Adding HTTP Status Code for failed #update action

### PR DESCRIPTION
**Pull request by romanos**
Hi. I noticed the HTTP status code for failed Update returns a 200 by default. This is fine in practice, but would be great to include 422 for those of us using status codes as an indicator for tests & functionality. Let me know, and thanks for the great project!

### CODE REVIEW

**Comment by schneems** [comment]
The idea is fine in concept. What does rails do by default? When you try to submit to an update and some model validation fails what status code do they use? It looks like tests are failing, but they're failing on main as well.

**Comment by schneems** [comment]
Tests should be fixed. Try pulling from main (not master) to rebase https://www.codetriage.com/rebase

**Comment by romanos** [comment]
@schneems sorry I missed this 2 months ago!

Good question I probably should have asked myself. The bog standard Rails implementation for `update` is:

```ruby
  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end
```

By default, it's format-dependent:
* In HTML, a 200 is returned
* In JSON, a 422 is returned

**Comment by schneems** [comment]
All responses from wicked are in HTML, so it would make sense to keep it with 200? It seems weird to return a valid webpage with a 4xx

**Comment by michael-garland** [comment]
> All responses from wicked are in HTML, so it would make sense to keep it with 200? It seems weird to return a valid webpage with a 4xx

I agree with this assessment. Re-rendering the edit page should be a 200.

**Comment by marckohlbrugge** [comment]
Could this be re-considered?

Turbo Drive requires a `422` response in order to render a page after a POST request. See https://turbo.hotwire.dev/handbook/drive#redirecting-after-a-form-submission

The current implementation of Wicked (returning a `200` and rendering the page, without a redirect) seems to fail with Turbo.

**Comment by marckohlbrugge** [comment]
For anyone else who runs into this issue with Hotwire / Turbo, here's a quick workaround you can add to your Wicked controller:

```ruby
  def update
    # … your existing code stays here
    # replace `resource` with whatever you're saving

    options = {}
    options[:status] = :unprocessable_entity if resource.invalid?

    render_wizard resource, options
  end
```

It's not perfect, because it relies on validations for checking validity. In some cases a record may be considered valid at first, but still fails to save to the database.

**Comment by atstockland** [comment]
Thanks @marckohlbrugge!  This works great, hopefully it won't be needed forever.

**Pull request closed without merging**
