### PR TITLE
Specify custom template in render_wizard method

### PR DESCRIPTION
**Pull request by aliahmed922**
While creating ERB template files in views for each specified step in `steps` method, there was no way to specify common template for them. This scenario appears when you've unknown step names that can come from database, an example of it could be a Survey that has different sections as steps. There you are required to specify a template that can be used for all of your steps. 

Just pass a template option to `render_wizard(nil, template: :your_erb_template_name)` method second parameter.

### CODE REVIEW

**Comment by schneems** [comment]
Hello. Thanks for the PR. I don't totally follow the desire here.

It seems like:

```ruby
render_wizard(template: :your_erb_template_name)
```

Is effectively the same as


```ruby
jump_to(:your_erb_template_name) 
render_wizard
```

**Comment by aliahmed922** [comment]
Hi @schneems, appreciate your feedback :)

Well I understand your alternate approach but the dilemma is that: in `jump_to` method, the step you passed should be added in the `steps` first and `:your_erb_template_name` is not a step rather it's a view template that you want to render. `jump_to` will transition you to the step you desire where as `render_wizard(template: :your_erb_template_name)` will just render a common view for dynamic steps from database.

Let me know if you still couldn't follow but I'm trying best to articulate my problem. P.S I also tried `jump_to` but the error I see is _The requested step did not match any steps defined for this controller._

**Comment by schneems** [comment]
Ahh, sorry I mis-spoke. `jump_to` would not be the right way to do this.

Here's where we determine the template to use https://github.com/zombocom/wicked/blob/a1e465d409f1225e1b4ef1fbc3eb0fa472c900ac/lib/wicked/controller/concerns/render_redirect.rb#L11.

Where `step` is just a helper method for `@step`. If you manually set `@step` right before calling `render_wizard` then I think it should work.

**Comment by schneems** [comment]
I'm still not quite sure of the use case here. I think maybe it's not a good fit for wicked. Sorry for taking so long to say so. Thanks for the PR!

**Pull request closed without merging**
